// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: balances.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBalance = `-- name: CreateBalance :one
INSERT INTO balances (
    id,
    user_id,
    asset,
    price,
    quantity
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, user_id, asset, price, quantity
`

type CreateBalanceParams struct {
	ID       pgtype.UUID
	UserID   pgtype.UUID
	Asset    string
	Price    pgtype.Numeric
	Quantity pgtype.Numeric
}

func (q *Queries) CreateBalance(ctx context.Context, arg CreateBalanceParams) (Balance, error) {
	row := q.db.QueryRow(ctx, createBalance,
		arg.ID,
		arg.UserID,
		arg.Asset,
		arg.Price,
		arg.Quantity,
	)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Asset,
		&i.Price,
		&i.Quantity,
	)
	return i, err
}

const decreaseBalanceQuantity = `-- name: DecreaseBalanceQuantity :exec
UPDATE balances
SET quantity = quantity - $3
WHERE user_id = $1
  AND asset = $2
`

type DecreaseBalanceQuantityParams struct {
	UserID   pgtype.UUID
	Asset    string
	Quantity pgtype.Numeric
}

func (q *Queries) DecreaseBalanceQuantity(ctx context.Context, arg DecreaseBalanceQuantityParams) error {
	_, err := q.db.Exec(ctx, decreaseBalanceQuantity, arg.UserID, arg.Asset, arg.Quantity)
	return err
}

const deleteBalance = `-- name: DeleteBalance :exec
DELETE FROM balances
WHERE id = $1
`

func (q *Queries) DeleteBalance(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBalance, id)
	return err
}

const getBalanceByID = `-- name: GetBalanceByID :one
SELECT id, user_id, asset, price, quantity
FROM balances
WHERE id = $1
`

func (q *Queries) GetBalanceByID(ctx context.Context, id pgtype.UUID) (Balance, error) {
	row := q.db.QueryRow(ctx, getBalanceByID, id)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Asset,
		&i.Price,
		&i.Quantity,
	)
	return i, err
}

const getUserAssetBalance = `-- name: GetUserAssetBalance :one
SELECT id, user_id, asset, price, quantity
FROM balances
WHERE user_id = $1
  AND asset = $2
`

type GetUserAssetBalanceParams struct {
	UserID pgtype.UUID
	Asset  string
}

func (q *Queries) GetUserAssetBalance(ctx context.Context, arg GetUserAssetBalanceParams) (Balance, error) {
	row := q.db.QueryRow(ctx, getUserAssetBalance, arg.UserID, arg.Asset)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Asset,
		&i.Price,
		&i.Quantity,
	)
	return i, err
}

const getUserBalances = `-- name: GetUserBalances :many
SELECT id, user_id, asset, price, quantity
FROM balances
WHERE user_id = $1
ORDER BY asset ASC
`

func (q *Queries) GetUserBalances(ctx context.Context, userID pgtype.UUID) ([]Balance, error) {
	rows, err := q.db.Query(ctx, getUserBalances, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Balance
	for rows.Next() {
		var i Balance
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Asset,
			&i.Price,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const increaseBalanceQuantity = `-- name: IncreaseBalanceQuantity :exec
UPDATE balances
SET quantity = quantity + $3
WHERE user_id = $1
  AND asset = $2
`

type IncreaseBalanceQuantityParams struct {
	UserID   pgtype.UUID
	Asset    string
	Quantity pgtype.Numeric
}

func (q *Queries) IncreaseBalanceQuantity(ctx context.Context, arg IncreaseBalanceQuantityParams) error {
	_, err := q.db.Exec(ctx, increaseBalanceQuantity, arg.UserID, arg.Asset, arg.Quantity)
	return err
}

const updateBalancePrice = `-- name: UpdateBalancePrice :exec
UPDATE balances
SET price = $3
WHERE user_id = $1
  AND asset = $2
`

type UpdateBalancePriceParams struct {
	UserID pgtype.UUID
	Asset  string
	Price  pgtype.Numeric
}

func (q *Queries) UpdateBalancePrice(ctx context.Context, arg UpdateBalancePriceParams) error {
	_, err := q.db.Exec(ctx, updateBalancePrice, arg.UserID, arg.Asset, arg.Price)
	return err
}
