// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: balances.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBalance = `-- name: CreateBalance :one
INSERT INTO balances (
    id,
    user_id,
    balance,
    asset_balance
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, user_id, balance, asset_balance, created_at, updated_at
`

type CreateBalanceParams struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Balance      int32
	AssetBalance []byte
}

func (q *Queries) CreateBalance(ctx context.Context, arg CreateBalanceParams) (Balance, error) {
	row := q.db.QueryRow(ctx, createBalance,
		arg.ID,
		arg.UserID,
		arg.Balance,
		arg.AssetBalance,
	)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.AssetBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBalance = `-- name: DeleteBalance :exec
DELETE FROM balances
WHERE id = $1
`

func (q *Queries) DeleteBalance(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBalance, id)
	return err
}

const deleteBalanceByUserID = `-- name: DeleteBalanceByUserID :exec
DELETE FROM balances
WHERE user_id = $1
`

func (q *Queries) DeleteBalanceByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBalanceByUserID, userID)
	return err
}

const getBalanceByID = `-- name: GetBalanceByID :one
SELECT id, user_id, balance, asset_balance, created_at, updated_at
FROM balances
WHERE id = $1
`

func (q *Queries) GetBalanceByID(ctx context.Context, id pgtype.UUID) (Balance, error) {
	row := q.db.QueryRow(ctx, getBalanceByID, id)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.AssetBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBalanceByUserID = `-- name: GetBalanceByUserID :one
SELECT id, user_id, balance, asset_balance, created_at, updated_at
FROM balances
WHERE user_id = $1
`

func (q *Queries) GetBalanceByUserID(ctx context.Context, userID pgtype.UUID) (Balance, error) {
	row := q.db.QueryRow(ctx, getBalanceByUserID, userID)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.AssetBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBalances = `-- name: ListBalances :many
SELECT id, user_id, balance, asset_balance, created_at, updated_at
FROM balances
ORDER BY user_id
`

func (q *Queries) ListBalances(ctx context.Context) ([]Balance, error) {
	rows, err := q.db.Query(ctx, listBalances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Balance
	for rows.Next() {
		var i Balance
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Balance,
			&i.AssetBalance,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssetBalance = `-- name: UpdateAssetBalance :one
UPDATE balances
SET asset_balance = $2
WHERE id = $1
RETURNING id, user_id, balance, asset_balance, created_at, updated_at
`

type UpdateAssetBalanceParams struct {
	ID           pgtype.UUID
	AssetBalance []byte
}

func (q *Queries) UpdateAssetBalance(ctx context.Context, arg UpdateAssetBalanceParams) (Balance, error) {
	row := q.db.QueryRow(ctx, updateAssetBalance, arg.ID, arg.AssetBalance)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.AssetBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBalance = `-- name: UpdateBalance :one
UPDATE balances
SET
    balance = $2,
    asset_balance = $3
WHERE id = $1
RETURNING id, user_id, balance, asset_balance, created_at, updated_at
`

type UpdateBalanceParams struct {
	ID           pgtype.UUID
	Balance      int32
	AssetBalance []byte
}

func (q *Queries) UpdateBalance(ctx context.Context, arg UpdateBalanceParams) (Balance, error) {
	row := q.db.QueryRow(ctx, updateBalance, arg.ID, arg.Balance, arg.AssetBalance)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.AssetBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBalanceAmount = `-- name: UpdateBalanceAmount :one
UPDATE balances
SET balance = $2
WHERE id = $1
RETURNING id, user_id, balance, asset_balance, created_at, updated_at
`

type UpdateBalanceAmountParams struct {
	ID      pgtype.UUID
	Balance int32
}

func (q *Queries) UpdateBalanceAmount(ctx context.Context, arg UpdateBalanceAmountParams) (Balance, error) {
	row := q.db.QueryRow(ctx, updateBalanceAmount, arg.ID, arg.Balance)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.AssetBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
