// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Balance struct {
	ID       pgtype.UUID
	UserID   pgtype.UUID
	Asset    string
	Price    pgtype.Numeric
	Quantity pgtype.Numeric
}

type Order struct {
	ID                pgtype.UUID
	Market            string
	Side              string
	Type              string
	UserID            pgtype.UUID
	Status            string
	Price             pgtype.Numeric
	Quantity          pgtype.Numeric
	RemainingQuantity pgtype.Numeric
	CreatedAt         pgtype.Timestamp
}

type Trade struct {
	ID           string
	Market       string
	BuyOrderID   string
	SellOrderID  string
	BuyerUserID  string
	SellerUserID string
	Price        int64
	Quantity     int64
	CreatedAt    pgtype.Timestamp
}

type User struct {
	ID        string
	Email     string
	Password  string
	Name      string
	CreatedAt pgtype.Timestamp
}
