// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelOrder = `-- name: CancelOrder :exec
UPDATE orders
SET status = 'CANCELLED'
WHERE id = $1
`

func (q *Queries) CancelOrder(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, cancelOrder, id)
	return err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    id,
    market,
    side,
    type,
    user_id,
    status,
    price,
    quantity,
    remaining_quantity,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, market, side, type, user_id, status, price, quantity, remaining_quantity, created_at
`

type CreateOrderParams struct {
	ID                pgtype.UUID
	Market            string
	Side              string
	Type              string
	UserID            pgtype.UUID
	Status            string
	Price             pgtype.Numeric
	Quantity          pgtype.Numeric
	RemainingQuantity pgtype.Numeric
	CreatedAt         pgtype.Timestamp
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.Market,
		arg.Side,
		arg.Type,
		arg.UserID,
		arg.Status,
		arg.Price,
		arg.Quantity,
		arg.RemainingQuantity,
		arg.CreatedAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Market,
		&i.Side,
		&i.Type,
		&i.UserID,
		&i.Status,
		&i.Price,
		&i.Quantity,
		&i.RemainingQuantity,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM orders
WHERE id = $1
`

func (q *Queries) DeleteOrder(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrder, id)
	return err
}

const getMatchingBuyOrders = `-- name: GetMatchingBuyOrders :many
SELECT id, market, side, type, user_id, status, price, quantity, remaining_quantity, created_at
FROM orders
WHERE market = $1
  AND side = 'BUY'
  AND status = 'OPEN'
  AND price >= $2
ORDER BY price DESC, created_at ASC
`

type GetMatchingBuyOrdersParams struct {
	Market string
	Price  pgtype.Numeric
}

func (q *Queries) GetMatchingBuyOrders(ctx context.Context, arg GetMatchingBuyOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, getMatchingBuyOrders, arg.Market, arg.Price)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.Side,
			&i.Type,
			&i.UserID,
			&i.Status,
			&i.Price,
			&i.Quantity,
			&i.RemainingQuantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMatchingSellOrders = `-- name: GetMatchingSellOrders :many
SELECT id, market, side, type, user_id, status, price, quantity, remaining_quantity, created_at
FROM orders
WHERE market = $1
  AND side = 'SELL'
  AND status = 'OPEN'
  AND price <= $2
ORDER BY price ASC, created_at ASC
`

type GetMatchingSellOrdersParams struct {
	Market string
	Price  pgtype.Numeric
}

func (q *Queries) GetMatchingSellOrders(ctx context.Context, arg GetMatchingSellOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, getMatchingSellOrders, arg.Market, arg.Price)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.Side,
			&i.Type,
			&i.UserID,
			&i.Status,
			&i.Price,
			&i.Quantity,
			&i.RemainingQuantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOpenBuyOrders = `-- name: GetOpenBuyOrders :many
SELECT id, market, side, type, user_id, status, price, quantity, remaining_quantity, created_at
FROM orders
WHERE market = $1
  AND side = 'BUY'
  AND status = 'OPEN'
ORDER BY price DESC, created_at ASC
`

func (q *Queries) GetOpenBuyOrders(ctx context.Context, market string) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOpenBuyOrders, market)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.Side,
			&i.Type,
			&i.UserID,
			&i.Status,
			&i.Price,
			&i.Quantity,
			&i.RemainingQuantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOpenSellOrders = `-- name: GetOpenSellOrders :many
SELECT id, market, side, type, user_id, status, price, quantity, remaining_quantity, created_at
FROM orders
WHERE market = $1
  AND side = 'SELL'
  AND status = 'OPEN'
ORDER BY price ASC, created_at ASC
`

func (q *Queries) GetOpenSellOrders(ctx context.Context, market string) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOpenSellOrders, market)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.Side,
			&i.Type,
			&i.UserID,
			&i.Status,
			&i.Price,
			&i.Quantity,
			&i.RemainingQuantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, market, side, type, user_id, status, price, quantity, remaining_quantity, created_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Market,
		&i.Side,
		&i.Type,
		&i.UserID,
		&i.Status,
		&i.Price,
		&i.Quantity,
		&i.RemainingQuantity,
		&i.CreatedAt,
	)
	return i, err
}

const getOrdersByMarket = `-- name: GetOrdersByMarket :many
SELECT id, market, side, type, user_id, status, price, quantity, remaining_quantity, created_at
FROM orders
WHERE market = $1
ORDER BY created_at DESC
`

func (q *Queries) GetOrdersByMarket(ctx context.Context, market string) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrdersByMarket, market)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.Side,
			&i.Type,
			&i.UserID,
			&i.Status,
			&i.Price,
			&i.Quantity,
			&i.RemainingQuantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByUser = `-- name: GetOrdersByUser :many
SELECT id, market, side, type, user_id, status, price, quantity, remaining_quantity, created_at
FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetOrdersByUser(ctx context.Context, userID pgtype.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrdersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.Side,
			&i.Type,
			&i.UserID,
			&i.Status,
			&i.Price,
			&i.Quantity,
			&i.RemainingQuantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT id, market, side, type, user_id, status, price, quantity, remaining_quantity, created_at
FROM orders
ORDER BY created_at DESC
`

func (q *Queries) ListOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.Side,
			&i.Type,
			&i.UserID,
			&i.Status,
			&i.Price,
			&i.Quantity,
			&i.RemainingQuantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrderFilled = `-- name: MarkOrderFilled :exec
UPDATE orders
SET status = 'FILLED',
    remaining_quantity = 0
WHERE id = $1
`

func (q *Queries) MarkOrderFilled(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOrderFilled, id)
	return err
}

const markOrderPartiallyFilled = `-- name: MarkOrderPartiallyFilled :exec
UPDATE orders
SET status = 'PARTIALLY_FILLED',
    remaining_quantity = $2
WHERE id = $1
`

type MarkOrderPartiallyFilledParams struct {
	ID                pgtype.UUID
	RemainingQuantity pgtype.Numeric
}

func (q *Queries) MarkOrderPartiallyFilled(ctx context.Context, arg MarkOrderPartiallyFilledParams) error {
	_, err := q.db.Exec(ctx, markOrderPartiallyFilled, arg.ID, arg.RemainingQuantity)
	return err
}

const updateOrderRemainingQuantity = `-- name: UpdateOrderRemainingQuantity :exec
UPDATE orders
SET remaining_quantity = $2
WHERE id = $1
`

type UpdateOrderRemainingQuantityParams struct {
	ID                pgtype.UUID
	RemainingQuantity pgtype.Numeric
}

func (q *Queries) UpdateOrderRemainingQuantity(ctx context.Context, arg UpdateOrderRemainingQuantityParams) error {
	_, err := q.db.Exec(ctx, updateOrderRemainingQuantity, arg.ID, arg.RemainingQuantity)
	return err
}
