// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trades.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTrade = `-- name: CreateTrade :one
INSERT INTO trades (
    id,
    market,
    buy_order_id,
    sell_order_id,
    buyer_user_id,
    seller_user_id,
    price,
    quantity,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, market, buy_order_id, sell_order_id, buyer_user_id, seller_user_id, price, quantity, created_at
`

type CreateTradeParams struct {
	ID           string
	Market       string
	BuyOrderID   string
	SellOrderID  string
	BuyerUserID  string
	SellerUserID string
	Price        int64
	Quantity     int64
	CreatedAt    pgtype.Timestamp
}

func (q *Queries) CreateTrade(ctx context.Context, arg CreateTradeParams) (Trade, error) {
	row := q.db.QueryRow(ctx, createTrade,
		arg.ID,
		arg.Market,
		arg.BuyOrderID,
		arg.SellOrderID,
		arg.BuyerUserID,
		arg.SellerUserID,
		arg.Price,
		arg.Quantity,
		arg.CreatedAt,
	)
	var i Trade
	err := row.Scan(
		&i.ID,
		&i.Market,
		&i.BuyOrderID,
		&i.SellOrderID,
		&i.BuyerUserID,
		&i.SellerUserID,
		&i.Price,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTrade = `-- name: DeleteTrade :exec
DELETE FROM trades
WHERE id = $1
`

func (q *Queries) DeleteTrade(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTrade, id)
	return err
}

const getMarketTradeCount = `-- name: GetMarketTradeCount :one
SELECT COUNT(*)
FROM trades
WHERE market = $1
`

func (q *Queries) GetMarketTradeCount(ctx context.Context, market string) (int64, error) {
	row := q.db.QueryRow(ctx, getMarketTradeCount, market)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMarketVolume = `-- name: GetMarketVolume :one
SELECT COALESCE(SUM(quantity), 0)
FROM trades
WHERE market = $1
`

func (q *Queries) GetMarketVolume(ctx context.Context, market string) (interface{}, error) {
	row := q.db.QueryRow(ctx, getMarketVolume, market)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getRecentTradesByMarket = `-- name: GetRecentTradesByMarket :many
SELECT id, market, buy_order_id, sell_order_id, buyer_user_id, seller_user_id, price, quantity, created_at
FROM trades
WHERE market = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetRecentTradesByMarketParams struct {
	Market string
	Limit  int32
}

func (q *Queries) GetRecentTradesByMarket(ctx context.Context, arg GetRecentTradesByMarketParams) ([]Trade, error) {
	rows, err := q.db.Query(ctx, getRecentTradesByMarket, arg.Market, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trade
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.BuyOrderID,
			&i.SellOrderID,
			&i.BuyerUserID,
			&i.SellerUserID,
			&i.Price,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTradeByID = `-- name: GetTradeByID :one
SELECT id, market, buy_order_id, sell_order_id, buyer_user_id, seller_user_id, price, quantity, created_at
FROM trades
WHERE id = $1
`

func (q *Queries) GetTradeByID(ctx context.Context, id string) (Trade, error) {
	row := q.db.QueryRow(ctx, getTradeByID, id)
	var i Trade
	err := row.Scan(
		&i.ID,
		&i.Market,
		&i.BuyOrderID,
		&i.SellOrderID,
		&i.BuyerUserID,
		&i.SellerUserID,
		&i.Price,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const getTradesByBuyer = `-- name: GetTradesByBuyer :many
SELECT id, market, buy_order_id, sell_order_id, buyer_user_id, seller_user_id, price, quantity, created_at
FROM trades
WHERE buyer_user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetTradesByBuyer(ctx context.Context, buyerUserID string) ([]Trade, error) {
	rows, err := q.db.Query(ctx, getTradesByBuyer, buyerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trade
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.BuyOrderID,
			&i.SellOrderID,
			&i.BuyerUserID,
			&i.SellerUserID,
			&i.Price,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTradesByMarket = `-- name: GetTradesByMarket :many
SELECT id, market, buy_order_id, sell_order_id, buyer_user_id, seller_user_id, price, quantity, created_at
FROM trades
WHERE market = $1
ORDER BY created_at DESC
`

func (q *Queries) GetTradesByMarket(ctx context.Context, market string) ([]Trade, error) {
	rows, err := q.db.Query(ctx, getTradesByMarket, market)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trade
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.BuyOrderID,
			&i.SellOrderID,
			&i.BuyerUserID,
			&i.SellerUserID,
			&i.Price,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTradesBySeller = `-- name: GetTradesBySeller :many
SELECT id, market, buy_order_id, sell_order_id, buyer_user_id, seller_user_id, price, quantity, created_at
FROM trades
WHERE seller_user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetTradesBySeller(ctx context.Context, sellerUserID string) ([]Trade, error) {
	rows, err := q.db.Query(ctx, getTradesBySeller, sellerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trade
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.BuyOrderID,
			&i.SellOrderID,
			&i.BuyerUserID,
			&i.SellerUserID,
			&i.Price,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTradesByUser = `-- name: GetTradesByUser :many
SELECT id, market, buy_order_id, sell_order_id, buyer_user_id, seller_user_id, price, quantity, created_at
FROM trades
WHERE buyer_user_id = $1
   OR seller_user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetTradesByUser(ctx context.Context, buyerUserID string) ([]Trade, error) {
	rows, err := q.db.Query(ctx, getTradesByUser, buyerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trade
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.BuyOrderID,
			&i.SellOrderID,
			&i.BuyerUserID,
			&i.SellerUserID,
			&i.Price,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrades = `-- name: ListTrades :many
SELECT id, market, buy_order_id, sell_order_id, buyer_user_id, seller_user_id, price, quantity, created_at
FROM trades
ORDER BY created_at DESC
`

func (q *Queries) ListTrades(ctx context.Context) ([]Trade, error) {
	rows, err := q.db.Query(ctx, listTrades)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trade
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.BuyOrderID,
			&i.SellOrderID,
			&i.BuyerUserID,
			&i.SellerUserID,
			&i.Price,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
